### PR TITLE
Made conversion to RxJava2

### PR DESCRIPTION
**Pull request by aballano**
Removed `Observable` and `Completable` streams as `Single` fulfils better the nature of `CallSpec` as a single return value thus making the testing simpler along the way.

Please note that this removes completely the dependency for RxJava1, so consider either bumping the version to something noticeable or change the master branch to make a proper differentiation in case you still want to maintain that version.

__Issue:__ N/A

__Dependencies:__
- [x] Unit Tests

### CODE REVIEW

**Comment by aballano** [comment]
image

**Comment by MyDogTom** [comment]
I would maintain both `rxJava 1.x` and `rxJava 2.x` together for a while in order to make transition more smooth for a client. I would also not change signature of existing methods but rather introduce new additional methods for `2.x` streams.

**Comment by aballano** [comment]
@MyDogTom If a client wants to transition, it should be possible to have a dependency for a `1.x` and `2.x` version at the same time, right? Same as you do with RxJava itself.

**Comment by yayaa** [comment]
I think i agree with @MyDogTom on this one, i'd keep old implementations (maybe deprecate even) and implement new version of them. So that, client would have chance to convert the request implementations not by big-bang-refactoring but small-partial-changes. 

@aballano and also sorry for leaving you alone here :) haha

**Comment by aballano** [comment]
@yayaa @MyDogTom Changes done!

**Comment by realdadfish** [comment]
Haven't looked at the actual implementation - but do we want to introduce `Maybe` support for single resource calls that would otherwise lead to 404's?

**Review by yayaa — APPROVED** [review]

**Review by dhartwich1991 — APPROVED** [review]

**Pull request merged**
