### PR TITLE
Bump Moshi to 1.5.0 and Moshi Lazy Adapters to 2.2

### PR DESCRIPTION
**Pull request by dhartwich1991**
_Bump Moshi Lazy Adapters library to 2.1._

- Library was bumped to 2.1 
- Improvements and fixes on the FallbackOnNull implementation
- Changes necessary for the migrations were made.

__Dependencies:__
- [x] Unit Tests

### CODE REVIEW

**Review by yayaa — APPROVED** [review]

**Comment by yayaa** [comment]
Bumped the version to 2.2 since we need a bugfix from that :)
Related Issue: https://jira.xing.hh/browse/XING-20474

**Comment by yayaa** [comment]
Bumped the version to 2.2 since we need a bugfix from that :)

**Comment by yayaa** [comment]
@aballano please see [the latest commit](https://github.com/xing/xing-android-sdk/pull/236/commits/6cab946063fcd9de3d325713b0a3323e64260b41). 

One test was failing as;

```
com.xing.api.resources.ContactsResourceTest > getContactPaths FAILED
    java.lang.IllegalArgumentException: No JsonAdapter for java.util.List<com.xing.api.data.contact.Users> annotated [@com.serjltt.moshi.adapters.Wrapped(failOnNotFound=true, path=[paths, ]), @com.xing.api.internal.json.ContactPath()]
        at com.squareup.moshi.Moshi.adapter(Moshi.java:116)
        at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:184)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:58)
        at com.xing.api.Converter.findAdapter(Converter.java:146)
        at com.xing.api.Converter.findAdapter(Converter.java:120)
        at com.xing.api.Converter.convertFromBody(Converter.java:91)
        at com.xing.api.RealCallSpec.parseResponse(RealCallSpec.java:320)
        at com.xing.api.RealCallSpec.execute(RealCallSpec.java:89)
        at com.xing.api.resources.ContactsResourceTest.getContactPaths(ContactsResourceTest.java:303)
```

I tried different approaches but none worked, so I revert the change you made. Please let me know if you can think of any other way, or is this OK for you?

**Comment by aballano** [comment]
Fine for me! If I remember correctly I also tried different approaches for that but ended up having to create a wrapper around the list, good that we can remove that now :)

**Pull request merged**
